# Generated by Django 3.1 on 2020-08-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='first_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addition',
            name='result',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='addition',
            name='second_number',
            field=models.IntegerField(),
        ),
    ]
