# Generated by Django 3.1 on 2020-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200825_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MNIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleImage', models.FileField(upload_to='input/')),
                ('mlResult', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Addition',
        ),
    ]
