# Generated by Django 3.1 on 2020-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20200825_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnist',
            name='mlResult',
            field=models.CharField(max_length=1000),
        ),
    ]
