# Generated by Django 3.1 on 2020-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20200825_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnist',
            name='sampleImage',
            field=models.FileField(blank=True, null=True, upload_to='input/'),
        ),
    ]
