# Generated by Django 3.1 on 2020-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200826_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnist',
            name='sampleImage',
            field=models.FileField(default=0, upload_to='input/'),
            preserve_default=False,
        ),
    ]
