# Generated by Django 3.1 on 2020-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20200826_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnist',
            name='mlResult',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
